# Generated by Django 5.0.3 on 2024-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'EU IREI'), (2, 'NÃO IREI')], default=0)),
                ('token', models.CharField(max_length=100)),
                ('hmac_digest', models.CharField(max_length=64)),
            ],
        ),
    ]
