# Generated by Django 5.0.3 on 2024-03-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0002_gift_alter_guest_hmac_digest_alter_guest_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guests', models.ForeignKey(limit_choices_to={'table__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='weddingSite.guest')),
            ],
        ),
    ]
