# Generated by Django 5.0.3 on 2024-03-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0003_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='guests',
        ),
        migrations.AddField(
            model_name='guest',
            name='fk_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='weddingSite.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='fk_guests',
            field=models.ManyToManyField(limit_choices_to={'table__isnull': True}, related_name='guest_tables', to='weddingSite.guest'),
        ),
    ]
