# Generated by Django 5.0.3 on 2024-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0006_alter_table_fk_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='fk_guests',
            field=models.ManyToManyField(related_name='guest_tables', to='weddingSite.guest'),
        ),
    ]
