# Generated by Django 5.0.3 on 2024-03-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0007_alter_table_fk_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('fk_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingSite.gift')),
                ('fk_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingSite.guest')),
            ],
        ),
    ]
