# Generated by Django 5.0.3 on 2024-03-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0009_alter_giftcart_fk_gift_alter_giftcart_fk_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCart',
        ),
    ]
