# Generated by Django 5.0.3 on 2024-03-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0010_delete_giftcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('fk_gift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingSite.gift')),
                ('fk_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddingSite.guest')),
            ],
        ),
    ]
