# Generated by Django 5.0.3 on 2024-03-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0011_giftcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcart',
            old_name='fk_gift',
            new_name='gift',
        ),
        migrations.RenameField(
            model_name='giftcart',
            old_name='fk_guest',
            new_name='guest',
        ),
    ]
