# Generated by Django 5.0.3 on 2024-03-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0012_rename_fk_gift_giftcart_gift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='fk_table',
            new_name='table',
        ),
    ]
