# Generated by Django 4.2.11 on 2024-03-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0013_rename_fk_table_guest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcart',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cart', to='weddingSite.guest'),
        ),
    ]
