# Generated by Django 5.0.3 on 2024-03-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0016_groupguest_remove_guest_hmac_digest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcart',
            name='guest',
        ),
        migrations.AddField(
            model_name='giftcart',
            name='guestGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cart', to='weddingSite.groupguest'),
        ),
    ]
