# Generated by Django 5.0.3 on 2024-03-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0017_remove_giftcart_guest_giftcart_guestgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupguest',
            name='hmac_digest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='status',
        ),
        migrations.AddField(
            model_name='groupguest',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDENTE'), (1, 'EU IREI'), (2, 'NÃO IREI')], default=0),
        ),
    ]
