# Generated by Django 4.2.11 on 2024-04-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0018_remove_groupguest_hmac_digest_remove_guest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
    ]
