# Generated by Django 4.2.11 on 2024-04-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0019_remove_gift_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
