# Generated by Django 5.0.3 on 2024-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0020_alter_gift_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupguest',
            name='type',
            field=models.IntegerField(choices=[(0, 'CONVIDADO'), (1, 'PADRINHOS')], default=0),
        ),
    ]
