# Generated by Django 5.0.3 on 2024-07-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingSite', '0021_groupguest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcart',
            name='gifts',
        ),
        migrations.AddField(
            model_name='giftcart',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cart', to='weddingSite.gift'),
        ),
    ]
